site_name: eventinhostech
repo_name: vilmarap/eventinhostech
repo_url: https://github.com/vilmarap/eventinhostech

theme:
  name: material
  language: pt
  palette: 
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: Switch to dark mode
    - scheme: slate 
      toggle: 
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/git
  features:
  - content.tabs.link
  - navigation.sections

nav:
  - Home: index.md
  - Agenda:
    - Programacao de 2023: 
      - Novembro: programacao2023/novembro2023.md
      - Dezembro: programacao2023/dezembro2023.md
    - Programação de 2024: 
      - Janeiro: programacao2024/janeiro2024.md

